server:
  port: 2001
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    # 指定数据源
    url: jdbc:mysql://112.74.17.146:8036/mate?useUnicode=true&characterEncode=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    # url: jdbc:mysql://localhost:8036/mate?useUnicode=true&characterEncode=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: GZ_smash8
    driver-class-name: com.mysql.cj.jdbc.Driver
file:
  rootPath: /usr/temp
# Logger Config
logging:
  level:
    com.cnsmash: debug
mybatis:
  mapper-locations: classpath*:com/cnsmash/**/*Mapper.xml